credentials:
  usernames:
    # --- Usuário Administrador ---
    admin:
      email: admin@email.com
      name: Administrador
      password: 'admin123' # Lembre-se de substituir por uma senha hasheada
    
    # --- Usuários Participantes ---
    participante1:
      email: p1@email.com
      name: Participante 1
      password: 'p1'
    participante2:
      email: p2@email.com
      name: Participante 2
      password: 'p2'
    participante3:
      email: p3@email.com
      name: Participante 3
      password: 'p3'
    participante4:
      email: p4@email.com
      name: Participante 4
      password: 'p4'
    participante5:
      email: p5@email.com
      name: Participante 5
      password: 'p5'
    participante6:
      email: p6@email.com
      name: Participante 6
      password: 'p6'
    participante7:
      email: p7@email.com
      name: Participante 7
      password: 'p7'
    participante8:
      email: p8@email.com
      name: Participante 8
      password: 'p8'
    participante9:
      email: p9@email.com
      name: Participante 9
      password: 'p9'
    participante10:
      email: p10@email.com
      name: Participante 10
      password: 'p10'

cookie:
  expiry_days: 30
  key: 'some_random_secret_key' # Mude para uma chave secreta aleatória
  name: 'escala_cookie'
