# config.yaml

credentials:
  usernames:
    # --- Usuário Administrador ---
    admin:
      email: admin@email.com
      name: Administrador
      password: 'admin123' # Substitua por uma senha hasheada
    # --- Usuários Participantes ---
    participante1:
      email: p1@email.com
      name: Participante 1
      password: 'p1'
    participante2:
      email: p2@email.com
      name: Participante 2
      password: 'p2'
    # Adicione os outros 8 participantes aqui...
    participante10:
      email: p10@email.com
      name: Participante 10
      password: 'p10'
cookie:
  expiry_days: 30
  key: 'some_random_secret_key' # Mude para uma chave secreta aleatória
  name: 'escala_cookie'
preauthorized:
  emails:
  - melsby@gmail.com
